### ISSUE TITLE
I get this error when I try to build the project (FFOSScene)

### ISSUE THREAD

**Issue by gery** [Fist-Full-of-Shrimp/FFOS-Unity-VR-Template#1]
ScriptableSingleton UnityEngine.XR.Interaction.Toolkit.InteractionLayerSettings already exists. This can happen if there are two copies of the asset or if you query the singleton in a constructor.
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun () (at /home/bokken/buildslave/unity/build/Editor/Mono/BuildPlayerWindow.cs:180)

I use unity editor version 2021.3.6f1

**Comment by TheGreatShelbino** [comment]
Looks like I duplicated the XR Interaction Toolkit on accident. Thanks for pointing this out! Should be fixed now.
